'use strict';

const STORIES = [
  {
    key: "fox_crow",
    title: "The Fox and the Crow",
    author: "Aesop's Fables",
    icon: "🦊",
    sentences: [
      {en:"A crow sat on a branch holding a piece of cheese.",        ja:"カラスがチーズを持って枝の上に座っていた。"},
      {en:"A fox looked up and saw the cheese.",                       ja:"キツネが見上げると、チーズが見えた。"},
      {en:"The fox wanted the cheese very much.",                      ja:"キツネはどうしてもそのチーズが欲しかった。"},
      {en:"\"What a beautiful bird you are!\" said the fox.",          ja:"「なんて美しい鳥だ！」とキツネは言った。"},
      {en:"\"Your feathers are so black and shiny.\"",                 ja:"「あなたの羽はとても黒くて輝いている。」"},
      {en:"\"You must surely have a beautiful voice too.\"",           ja:"「きっと美しい声も持っているに違いない。」"},
      {en:"\"Please sing for me, dear crow.\"",                        ja:"「どうか私のために歌ってください。」"},
      {en:"The crow was very pleased to hear this.",                   ja:"カラスはこれを聞いてとても喜んだ。"},
      {en:"She opened her mouth wide to sing.",                        ja:"彼女は歌おうと大きく口を開けた。"},
      {en:"The piece of cheese fell to the ground.",                   ja:"チーズの切れ端が地面に落ちた。"},
      {en:"The fox quickly snatched it up.",                           ja:"キツネはすばやくそれを拾い上げた。"},
      {en:"\"Thank you,\" said the fox with a smile.",                 ja:"「ありがとう」とキツネは笑いながら言った。"},
      {en:"\"You have a fine voice, but you have no wisdom.\"",        ja:"「声は美しいが、知恵がない。」"},
      {en:"Moral: Do not trust those who flatter you.",                ja:"教訓：お世辞を言う人を信用してはいけない。"},
    ]
  },
  {
    key: "tortoise_hare",
    title: "The Tortoise and the Hare",
    author: "Aesop's Fables",
    icon: "🐢",
    sentences: [
      {en:"A hare always laughed at the slow tortoise.",               ja:"ウサギはいつも遅いカメを笑っていた。"},
      {en:"\"I am so much faster than you,\" said the hare.",          ja:"「僕はあなたよりずっと速い」とウサギは言った。"},
      {en:"The tortoise replied, \"Let us have a race.\"",             ja:"カメは答えた。「競争しましょう。」"},
      {en:"The hare laughed but agreed.",                              ja:"ウサギは笑ったが同意した。"},
      {en:"The race began and the hare ran far ahead.",                ja:"競争が始まり、ウサギははるか先に走り出した。"},
      {en:"He stopped to rest under a shady tree.",                    ja:"彼は木陰で休もうと立ち止まった。"},
      {en:"\"The tortoise will never catch me,\" he thought.",         ja:"「カメは絶対に追いつけない」と彼は思った。"},
      {en:"He closed his eyes and fell fast asleep.",                  ja:"彼は目を閉じてぐっすり眠ってしまった。"},
      {en:"The tortoise walked slowly but never stopped.",             ja:"カメはゆっくりだが決して立ち止まらなかった。"},
      {en:"He passed the sleeping hare without a sound.",              ja:"彼は音もなく眠るウサギを追い越した。"},
      {en:"At last the tortoise crossed the finish line.",             ja:"ついにカメがゴールラインを越えた。"},
      {en:"The hare woke up and ran as fast as he could.",             ja:"ウサギは目を覚まして全力で走った。"},
      {en:"But the tortoise had already won the race.",                ja:"しかしカメはすでに競争に勝っていた。"},
      {en:"Moral: Slow and steady wins the race.",                     ja:"教訓：ゆっくりでも着実に進めば勝てる。"},
    ]
  },
  {
    key: "boy_wolf",
    title: "The Boy Who Cried Wolf",
    author: "Aesop's Fables",
    icon: "🐺",
    sentences: [
      {en:"A young shepherd boy watched sheep on a hill.",             ja:"若い羊飼いの少年が丘で羊の番をしていた。"},
      {en:"He was bored and wanted some excitement.",                  ja:"彼は退屈していて刺激が欲しかった。"},
      {en:"He decided to play a trick on the villagers.",              ja:"彼は村人たちをだますことにした。"},
      {en:"\"Wolf! Wolf!\" he cried as loud as he could.",             ja:"「オオカミだ！オオカミだ！」と彼は叫んだ。"},
      {en:"The villagers ran up the hill to help.",                    ja:"村人たちが助けに丘を駆け上った。"},
      {en:"But there was no wolf anywhere.",                           ja:"しかしどこにもオオカミはいなかった。"},
      {en:"The boy laughed at them.",                                  ja:"少年は彼らを笑った。"},
      {en:"The next day he did the same thing again.",                 ja:"翌日も彼は同じことをした。"},
      {en:"Again the villagers came running.",                         ja:"また村人たちが走ってきた。"},
      {en:"Again there was no wolf at all.",                           ja:"またオオカミはまったくいなかった。"},
      {en:"Then one day a real wolf appeared on the hill.",            ja:"そしてある日、本物のオオカミが丘に現れた。"},
      {en:"\"Wolf! Wolf!\" the boy cried in terror.",                  ja:"「オオカミだ！」と少年は恐怖で叫んだ。"},
      {en:"But this time no one believed him.",                        ja:"しかし今度は誰も信じなかった。"},
      {en:"No one came to help the boy.",                              ja:"少年を助けに来る人は誰もいなかった。"},
      {en:"Moral: Nobody believes a liar, even when telling the truth.", ja:"教訓：うそつきは真実を話しても信じてもらえない。"},
    ]
  },
  {
    key: "ant_grasshopper",
    title: "The Ant and the Grasshopper",
    author: "Aesop's Fables",
    icon: "🐜",
    sentences: [
      {en:"All summer long the ant worked very hard.",                 ja:"夏の間中、アリは一生懸命働いた。"},
      {en:"She collected food and stored it for winter.",              ja:"彼女は食べ物を集めて冬のために蓄えた。"},
      {en:"The grasshopper played music and sang all day.",            ja:"キリギリスは一日中音楽を弾いて歌っていた。"},
      {en:"\"Why do you work so hard?\" asked the grasshopper.",       ja:"「なぜそんなに働くの？」とキリギリスは尋ねた。"},
      {en:"\"Come and enjoy the warm summer with me!\"",               ja:"「一緒に暖かい夏を楽しもうよ！」"},
      {en:"The ant replied, \"I am preparing for winter.\"",           ja:"アリは答えた。「冬の準備をしているの。」"},
      {en:"\"You should do the same, my friend.\"",                    ja:"「あなたも同じようにすべきよ。」"},
      {en:"The grasshopper laughed and kept on playing.",              ja:"キリギリスは笑って演奏を続けた。"},
      {en:"When winter came, the ant had plenty of food.",             ja:"冬が来ると、アリには十分な食べ物があった。"},
      {en:"The grasshopper had nothing to eat at all.",                ja:"キリギリスには食べるものが何もなかった。"},
      {en:"He went to the ant's house and begged for food.",           ja:"彼はアリの家へ行って食べ物を乞うた。"},
      {en:"The ant said, \"You sang all summer long.\"",               ja:"アリは言った。「あなたは夏中歌っていたでしょ。」"},
      {en:"\"Now you can dance through the cold winter.\"",            ja:"「今度は寒い冬の間、踊ればいい。」"},
      {en:"Moral: It is wise to prepare for the future.",              ja:"教訓：将来に備えることが賢明だ。"},
    ]
  },
  {
    key: "lion_mouse",
    title: "The Lion and the Mouse",
    author: "Aesop's Fables",
    icon: "🦁",
    sentences: [
      {en:"A lion was sleeping in the forest.",                        ja:"ライオンが森の中で眠っていた。"},
      {en:"A small mouse ran over his face.",                          ja:"小さなネズミが彼の顔の上を走った。"},
      {en:"The lion woke up and caught the mouse.",                    ja:"ライオンは目を覚まし、ネズミを捕まえた。"},
      {en:"He was about to eat it.",                                   ja:"彼はそれを食べようとしていた。"},
      {en:"\"Please let me go!\" cried the mouse.",                    ja:"「どうか逃がしてください！」とネズミは叫んだ。"},
      {en:"\"Someday I will help you in return.\"",                    ja:"「いつかお返しにお役に立ちます。」"},
      {en:"The lion laughed but let the mouse go.",                    ja:"ライオンは笑ったがネズミを逃がした。"},
      {en:"Soon after, the lion was caught in a hunter's net.",        ja:"まもなくライオンが猟師の網に捕まった。"},
      {en:"He roared loudly but could not escape.",                    ja:"彼は大きく吠えたが逃げられなかった。"},
      {en:"The little mouse heard the lion's roar.",                   ja:"小さなネズミがライオンの咆哮を聞いた。"},
      {en:"She ran to the net and began to bite it.",                  ja:"彼女は網へ走り、噛み始めた。"},
      {en:"She chewed through the ropes with her sharp teeth.",        ja:"彼女は鋭い歯でロープを噛み切った。"},
      {en:"The lion was free at last.",                                ja:"ライオンはついに自由になった。"},
      {en:"Moral: Even the small can help the mighty.",                ja:"教訓：小さい者でも強い者を助けることができる。"},
    ]
  },
  {
    key: "alice",
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll (1865)",
    icon: "🐇",
    sentences: [
      {en:"Alice was beginning to feel very tired.",                   ja:"アリスはとても疲れを感じ始めていた。"},
      {en:"She sat beside her sister on the riverbank.",               ja:"彼女は川のほとりで姉の隣に座っていた。"},
      {en:"Her sister's book had no pictures in it.",                  ja:"姉の本には絵が一枚もなかった。"},
      {en:"\"What is the use of a book without pictures?\" thought Alice.", ja:"「絵のない本に何の意味があるの？」とアリスは思った。"},
      {en:"Suddenly a White Rabbit ran past her.",                     ja:"突然、白いウサギが彼女のそばを走り過ぎた。"},
      {en:"The White Rabbit had bright pink eyes.",                    ja:"白ウサギには明るいピンクの目があった。"},
      {en:"\"Oh dear! I shall be too late!\" said the Rabbit.",        ja:"「大変だ！遅刻してしまう！」とウサギは言った。"},
      {en:"The Rabbit took a watch from its pocket.",                  ja:"ウサギはポケットから時計を取り出した。"},
      {en:"It looked at the watch and hurried on.",                    ja:"時計を見てから急いで行ってしまった。"},
      {en:"Alice had never seen a rabbit with a pocket watch.",        ja:"アリスはポケット時計を持ったウサギを見たことがなかった。"},
      {en:"She ran across the field after the Rabbit.",                ja:"彼女は野原をウサギの後を追って走った。"},
      {en:"She saw it pop down a large hole under a hedge.",           ja:"生け垣の下の大きな穴に飛び込むのを見た。"},
      {en:"Alice jumped into the hole without thinking twice.",         ja:"アリスは迷わず穴の中に飛び込んだ。"},
      {en:"The rabbit-hole went down, down, down.",                    ja:"ウサギの穴はどんどん下へと続いていた。"},
      {en:"It seemed to have no bottom at all.",                       ja:"底がまったくないように思えた。"},
      {en:"She was falling for a very long time.",                     ja:"彼女はとても長い間落ち続けていた。"},
    ]
  },
  {
    key: "gift_magi",
    title: "The Gift of the Magi",
    author: "O. Henry (1905)",
    icon: "🎁",
    sentences: [
      {en:"One dollar and eighty-seven cents.",                        ja:"1ドル87セント。"},
      {en:"That was all that Della had saved.",                        ja:"それがデラの貯えたすべてだった。"},
      {en:"She counted it three times to be sure.",                    ja:"彼女は確かめるために3回数えた。"},
      {en:"And the next day would be Christmas.",                      ja:"そして翌日はクリスマスだった。"},
      {en:"There was nothing to do but sit down and cry.",             ja:"座って泣く以外に何もできなかった。"},
      {en:"Jim and Della were poor but happy.",                        ja:"ジムとデラは貧しかったが幸せだった。"},
      {en:"They had two treasures they were very proud of.",           ja:"彼らには誇りに思う宝が二つあった。"},
      {en:"One was Jim's gold watch from his grandfather.",            ja:"一つはジムの祖父から受け継いだ金時計だった。"},
      {en:"The other was Della's long and beautiful hair.",            ja:"もう一つはデラの長くて美しい髪だった。"},
      {en:"Della's hair fell below her knees when let down.",          ja:"デラの髪は下ろすと膝の下まで届いた。"},
      {en:"She decided to sell her hair to buy Jim a gift.",           ja:"彼女はジムへのプレゼントを買うために髪を売ることにした。"},
      {en:"She received twenty dollars for her hair.",                 ja:"彼女は髪の毛で20ドルを受け取った。"},
      {en:"She bought a beautiful platinum chain for his watch.",      ja:"彼女は彼の時計のための美しい白金の鎖を買った。"},
      {en:"Jim had sold his watch to buy combs for Della's hair.",     ja:"ジムはデラの髪のための飾り櫛を買うために時計を売っていた。"},
      {en:"Their gifts were both useless, but full of love.",          ja:"二人のプレゼントは役に立たないが、愛に満ちていた。"},
    ]
  },
  {
    key: "tell_tale_heart",
    title: "The Tell-Tale Heart",
    author: "Edgar Allan Poe (1843)",
    icon: "💀",
    sentences: [
      {en:"True! Nervous, very nervous I had been.",                   ja:"本当だ！私は神経質で、ひどく神経質だった。"},
      {en:"But why do you say that I am mad?",                        ja:"でもなぜあなたは私が狂っていると言うのか？"},
      {en:"The disease had sharpened my senses.",                     ja:"病が私の感覚をとても鋭くしていた。"},
      {en:"Above all, the sense of hearing was very sharp.",          ja:"特に、聴覚がとても鋭くなっていた。"},
      {en:"I heard things in the heavens and in the earth.",          ja:"天と地のあらゆるものが聞こえた。"},
      {en:"Now I will tell you the whole story calmly.",              ja:"今から落ち着いて全部の話をしよう。"},
      {en:"There was no reason at all to hate the old man.",          ja:"老人を憎む理由はまったくなかった。"},
      {en:"He had never wronged me in any way.",                     ja:"彼は決して私に悪いことをしたことがなかった。"},
      {en:"He had never given me any insult.",                       ja:"彼は私を侮辱したことも一度もなかった。"},
      {en:"I think I even loved the old man.",                       ja:"老人のことを愛していたとさえ思う。"},
      {en:"But he had one very pale blue eye.",                      ja:"しかし彼にはとても薄い青い目が一つあった。"},
      {en:"It looked like the eye of a vulture.",                    ja:"それはハゲタカの目のように見えた。"},
      {en:"Whenever it fell upon me, my blood ran cold.",            ja:"その目が私に向けられるたびに、血が凍りついた。"},
      {en:"And so, very slowly, I decided to act.",                  ja:"そこで、ごくゆっくりと、私は行動することにした。"},
    ]
  },
  {
    key: "romeo_juliet",
    title: "Romeo and Juliet – Famous Lines",
    author: "William Shakespeare (1597)",
    icon: "🌹",
    sentences: [
      {en:"Two households, both alike in dignity.",                   ja:"二つの名門家がある、どちらも同じく誇り高い。"},
      {en:"In fair Verona, where we lay our scene.",                  ja:"美しいヴェローナの地、そこが舞台だ。"},
      {en:"From ancient grudge break to new mutiny.",                 ja:"古くからの恨みが新たな争いへと発展する。"},
      {en:"Where civil blood makes civil hands unclean.",             ja:"市民の血が市民の手を汚す。"},
      {en:"A pair of star-crossed lovers take their life.",           ja:"運命に引き裂かれた恋人たちが命を絶つ。"},
      {en:"But, soft! What light through yonder window breaks?",     ja:"しかし待て！あの窓からどんな光が差し込むのか？"},
      {en:"It is the east, and Juliet is the sun.",                  ja:"それは東だ、そしてジュリエットは太陽だ。"},
      {en:"What's in a name? A rose by any other name would smell as sweet.", ja:"名前に何があるのか？バラは他の名前でも同じように香る。"},
      {en:"O Romeo, Romeo! Wherefore art thou Romeo?",               ja:"ロミオよ、ロミオ！なぜあなたはロミオなの？"},
      {en:"Good night, good night! Parting is such sweet sorrow.", ja:"おやすみ、おやすみ！別れはこんなにも甘い悲しみだ。"},
      {en:"These violent delights have violent ends.",               ja:"激しい喜びは激しい終わりを迎える。"},
      {en:"What light through yonder window breaks?",               ja:"あの窓からどんな光が差し込むのか？"},
      {en:"For never was a story of more woe.",                     ja:"これほど悲しい物語は今までになかった。"},
      {en:"Than this of Juliet and her Romeo.",                     ja:"このジュリエットとロミオの物語のように。"},
    ]
  },
  {
    key: "wizard_oz",
    title: "The Wonderful Wizard of Oz",
    author: "L. Frank Baum (1900)",
    icon: "🌈",
    sentences: [
      {en:"Dorothy lived in the great Kansas prairies.",             ja:"ドロシーはカンザスの広大な草原に住んでいた。"},
      {en:"Her house was small and gray.",                          ja:"彼女の家は小さくて灰色だった。"},
      {en:"Uncle Henry never laughed.",                            ja:"ヘンリーおじさんは決して笑わなかった。"},
      {en:"He worked hard from morning until night.",              ja:"彼は朝から晩まで一生懸命働いた。"},
      {en:"Dorothy's dog Toto made her laugh every day.",          ja:"ドロシーの犬トトは毎日彼女を笑わせた。"},
      {en:"One day a great cyclone came to Kansas.",               ja:"ある日、巨大な竜巻がカンザスにやってきた。"},
      {en:"The wind lifted the house high into the air.",          ja:"風が家を高く空中に持ち上げた。"},
      {en:"Dorothy and Toto were carried far away.",               ja:"ドロシーとトトは遠くに運ばれた。"},
      {en:"The house landed softly in a beautiful land.",          ja:"家は美しい土地にそっと着陸した。"},
      {en:"A little old woman stood before Dorothy.",              ja:"小さな老婆がドロシーの前に立っていた。"},
      {en:"\"Are you a good witch or a bad witch?\" she asked.",  ja:"「あなたは良い魔女ですか、悪い魔女ですか？」と彼女は聞いた。"},
      {en:"\"I am not a witch at all,\" said Dorothy.",           ja:"「私は魔女じゃないわ」とドロシーは言った。"},
      {en:"\"Follow the yellow brick road,\" said the witch.",    ja:"「黄色いレンガの道を行きなさい」と魔女は言った。"},
      {en:"\"It will take you to the Emerald City.\"",            ja:"「それがあなたをエメラルド・シティへ連れて行くでしょう。」"},
      {en:"There you will find the wonderful Wizard of Oz.",      ja:"そこで素晴らしいオズの魔法使いに会えます。"},
    ]
  },
];
